"""empty message

Revision ID: 24b1b61c7b3
Revises: 11212701bb9
Create Date: 2015-09-07 01:10:46.250322

"""

# revision identifiers, used by Alembic.
revision = '24b1b61c7b3'
down_revision = '11212701bb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
