"""empty message

Revision ID: 3b908eed9ea
Revises: 24b1b61c7b3
Create Date: 2015-09-07 01:13:04.829468

"""

# revision identifiers, used by Alembic.
revision = '3b908eed9ea'
down_revision = '24b1b61c7b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
