"""empty message

Revision ID: 2fe37ae412
Revises: f9105fff3c
Create Date: 2015-09-06 22:45:11.642409

"""

# revision identifiers, used by Alembic.
revision = '2fe37ae412'
down_revision = 'f9105fff3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
