"""empty message

Revision ID: 1040746be6b
Revises: f98e031c81
Create Date: 2015-11-25 03:07:21.289699

"""

# revision identifiers, used by Alembic.
revision = '1040746be6b'
down_revision = 'b771d6b356'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatars', sa.Column('is_alive', sa.Integer(), nullable=True))
    op.add_column('avatars', sa.Column('movement_range', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatars', 'movement_range')
    op.drop_column('avatars', 'is_alive')
    ### end Alembic commands ###
