"""empty message

Revision ID: 1201b48494b
Revises: 10e3eee239
Create Date: 2015-12-02 08:20:04.424740

"""

# revision identifiers, used by Alembic.
revision = '1201b48494b'
down_revision = '10e3eee239'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
