"""empty message

Revision ID: 1f62b38cbf4
Revises: 26d0b8c3da5
Create Date: 2015-11-23 00:30:42.427127

"""

# revision identifiers, used by Alembic.
revision = '1f62b38cbf4'
down_revision = '26d0b8c3da5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worldmap', sa.Column('has_city', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worldmap', 'has_city')
    ### end Alembic commands ###
