"""empty message

Revision ID: 20ae59e47c2
Revises: 3bc8283dc27
Create Date: 2017-02-16 19:48:18.322272

"""

# revision identifiers, used by Alembic.
revision = '20ae59e47c2'
down_revision = '3bc8283dc27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publisher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('primary_author', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('series_number', sa.Integer(), nullable=True),
    sa.Column('published', sa.Integer(), nullable=True),
    sa.Column('small_blurb', sa.Text(), nullable=True),
    sa.Column('large_review', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['primary_author'], ['author.id'], ),
    sa.ForeignKeyConstraint(['publisher'], ['publisher.id'], ),
    sa.ForeignKeyConstraint(['series'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('power_points', sa.Column('player_status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('power_points', 'player_status')
    op.drop_table('books')
    op.drop_table('publisher')
    op.drop_table('author')
    op.drop_table('series')
    ### end Alembic commands ###
