"""empty message

Revision ID: 2426196d570
Revises: 20ae59e47c2
Create Date: 2017-02-16 21:32:25.062842

"""

# revision identifiers, used by Alembic.
revision = '2426196d570'
down_revision = '20ae59e47c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
