"""empty message

Revision ID: 26d0b8c3da5
Revises: 3192cb55e01
Create Date: 2015-11-23 00:08:46.049067

"""

# revision identifiers, used by Alembic.
revision = '26d0b8c3da5'
down_revision = '3192cb55e01'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
