"""empty message

Revision ID: 3192cb55e01
Revises: 56740b17c07
Create Date: 2015-11-23 00:08:17.085247

"""

# revision identifiers, used by Alembic.
revision = '3192cb55e01'
down_revision = '56740b17c07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
