"""empty message

Revision ID: 3bc8283dc27
Revises: 10e3eee239
Create Date: 2015-12-25 16:55:58.030476

"""

# revision identifiers, used by Alembic.
revision = '3bc8283dc27'
down_revision = '10e3eee239'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('power_points', sa.Column('is_ready', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('power_points', 'is_ready')
    ### end Alembic commands ###
