"""empty message

Revision ID: 60204fc513
Revises: 1f62b38cbf4
Create Date: 2015-11-23 00:31:32.332495

"""

# revision identifiers, used by Alembic.
revision = '60204fc513'
down_revision = '1f62b38cbf4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
