"""empty message

Revision ID: b771d6b356
Revises: f98e031c81
Create Date: 2015-11-24 16:03:54.698138

"""

# revision identifiers, used by Alembic.
revision = 'b771d6b356'
down_revision = 'f98e031c81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
