"""empty message

Revision ID: f98e031c81
Revises: 60204fc513
Create Date: 2015-11-23 21:30:31.364363

"""

# revision identifiers, used by Alembic.
revision = 'f98e031c81'
down_revision = '60204fc513'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
