points_table = {
    1: {
        "Shape Land":3,
        "Shape Climate":2,
        "Create Race":22,
        "Create Subrace": 12,
        "Command Race": 8,
        "Command City": 6,
        "Advance Race": 10,
        "Advance City": 8,
        "Purify Civ": 5,
        "Corrupt Civ": 4,
        "Purify City": 4,
        "Corrupt City": 3,
        "Event": 10,
        "Create Order": 8,
        "Command Order": 4,
        "Create Avatar": 10,
        "Command Avatar": 2,
        "Catastrophe": 10,
        },
    2: {
        "Shape Land":5,
        "Shape Climate":4,
        "Create Race":6,
        "Create Subrace": 4,
        "Command Race": 4,
        "Command City": 4,
        "Advance Race": 5,
        "Advance City": 4,
        "Purify Civ": 3,
        "Corrupt Civ": 3,
        "Purify City": 3,
        "Corrupt City": 2,
        "Event": 7,
        "Create Order": 6,
        "Command Order": 3,
        "Create Avatar": 7,
        "Command Avatar": 1,
        "Catastrophe": 10,
        },
    3: {
        "Shape Land":8,
        "Shape Climate":6,
        "Create Race":15,
        "Create Subrace": 10,
        "Command Race": 3,
        "Command City": 2,
        "Advance Race": 6,
        "Advance City": 5,
        "Purify Civ": 4,
        "Corrupt Civ": 3,
        "Purify City": 3,
        "Corrupt City": 2,
        "Event": 9,
        "Create Order": 4,
        "Command Order": 2,
        "Create Avatar": 8,
        "Command Avatar": 1,
        "Catastrophe": 10,
        },
    }
